refactor Pagination component
cockroachdb/admin-ui-components pull request #35
Opened 2020-10-12 12:29 UTC by koorosh

Partially fixes https://github.com/cockroachdb/cockroach/issues/54513 (3rd item)

Previously, Pagination component has been created but not used
as a single version for pagination. In addition, Ant design components
were imported right into page views with duplicated styles and it brought
us into situation with multiple versions of almost identical functionality.

This change is a step forward to remove duplicated components and use single
version of pagination component. Along with this, `Pagination` component is
refactored with respect to latest designs.

`ResultsPerPageLabel` component is extracted as a standalone component which
displays number of results per paginated view. This functionality is used in
several places so it's a good time to refactor it as well.

2020-10-12 12:29 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/admin-ui-components/35)
<!-- Reviewable:end -->

2020-10-13 19:57 UTC, nathanstilwell requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/35)* status: all files reviewed, 1 unresolved discussion (waiting on @koorosh)

___
*[src/pagination/pagination.module.scss, line 1 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/35#-MJYXV_W0BzKFZlywToO:-MJYXV_XE2TYEFFN8ToO:bw3ozed) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/4b9943ea55289c9e428b1046b1064c1a5f71ae87/src/pagination/pagination.module.scss#L1)):*
> ```SCSS
> @import '../core/index.module';
> ```

I think we prefer double quotes for imports


<!-- Sent from Reviewable.io -->

2020-10-16 13:03 UTC, koorosh commented
> > Reviewed 9 of 9 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/35)_ status: all files reviewed, 1 unresolved discussion (waiting on @koorosh)
> 
> _[src/pagination/pagination.module.scss, line 1 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/35#-MJYXV_W0BzKFZlywToO:-MJYXV_XE2TYEFFN8ToO:bw3ozed) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/4b9943ea55289c9e428b1046b1064c1a5f71ae87/src/pagination/pagination.module.scss#L1)):_
> 
> > ```css-scss
> > @import '../core/index.module';
> > ```
> 
> I think we prefer double quotes for imports

Done

2020-10-20 13:38 UTC, nathanstilwell approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/35)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-20 18:04 UTC, merged