fix barCharts rendering for zero values
cockroachdb/admin-ui-components pull request #41
Opened 2020-11-20 17:49 UTC by koorosh

Resolves #40 

This is a fix for regression that was caused when d3 package was
replaced by d3-scale package and others. Latest version of `d3-scale`
package introduced change related to the issue https://github.com/d3/d3-scale/issues/117
that caused to half fill barChart for 0 value.

Now, `normalizeClosedDomain` checks if domain start and end values
are equal or not, and in case they are equal, it increases last value
by one. Note, it doesn't change actual values, but only domain range of
possible values.

Most of the time barChart renders bars with range from 0% to 100% and
it should show 0% value when we have values [0, 0].
- With introduced "breaking" change in d3-scale, it returns middle point
for range [0, 0] and it equals 50% (for range0 from % to 100%).
- With fix and as it was before, for 0 value scaling within [0, 0] domain
will return 0%

2020-11-20 17:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/admin-ui-components/41)
<!-- Reviewable:end -->

2020-11-23 19:56 UTC, dhartunian requested changes
@koorosh if the goal is to explicitly bring back support for the "0" graph, can't we just choose not to render a graph at all when the values are zero? I feel like there should be a better solution for the case when we don't want a graph to render. Doesn't d3 support this more directly?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/41#-:-MMqek9WB6N6G11utkbo:b-3aa8i0)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @dhartunian and @elkmaster)



<!-- Sent from Reviewable.io -->

2020-11-24 12:07 UTC, koorosh reviewed
I don't feel that it's a good option to conditionally render or not to render component, because it has to show label with bar as well (0% [ empty bar ]). 
D3 isn't responsible for rendering elements in our case so we can't rely on this as well. D3 only provides us utility function to scale the value proportionally to barCharts width.

Before, scaling behavior wasn't defined for cases like this and it worked the way we needed, but now additional checks have to be done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/41#-:-MMtvyN36pZiZWhdQVf2:b-liasmb)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @elkmaster)



<!-- Sent from Reviewable.io -->

2020-11-24 20:55 UTC, dhartunian approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks for looking into this. Interesting problem. I don't see an easy way to avoid introducing this helper function.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/41#-:-MMw1Faa0tQ6QPrFYM2L:b-rvlx2h)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elkmaster)



<!-- Sent from Reviewable.io -->

2020-11-25 09:52 UTC, merged