ui: DB Console branding refresh
cockroachdb/admin-ui-components pull request #44
Opened 2020-11-25 17:11 UTC by elkmaster

Updated  primary color on buttons to purple, new link colors to represent new branding pallete.

Resolves: #56959

![Screenshot 2020-11-25 at 19 11 16](https://user-images.githubusercontent.com/12850886/100260385-01442900-2f52-11eb-9ed5-fa1b9997dd9f.png)

2020-11-25 17:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/admin-ui-components/44)
<!-- Reviewable:end -->

2020-11-27 11:25 UTC, koorosh requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/44)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @elkmaster)

*[a discussion](https://reviewable.io/reviews/cockroachdb/admin-ui-components/44#-MN8Pa_v5SwxxsdtPKof:-MN8Pa_v5SwxxsdtPKog:bfnru89) (no related file):*
`Anchor` component has a link which still has old blue color defined in
`src/anchor/anchor.module.scss`. Can you change this color as well?

![Screen Shot 2020-11-27 at 1.14.06 PM.png](https://files.reviewableusercontent.io/images/reviewable/3106437/mQGU0PlVw9tdMr-JUeOQwi6A/Screen%20Shot%202020-11-27%20at%201.14.06%20PM.png)

---


<!-- Sent from Reviewable.io -->

2020-12-01 22:27 UTC, nathanstilwell approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/44)* status: all files reviewed, 1 unresolved discussion (waiting on @koorosh)

*[a discussion](https://reviewable.io/reviews/cockroachdb/admin-ui-components/44#-MN8Pa_v5SwxxsdtPKof:-MNVOotu5qO-1amGStmN:b-759be6) (no related file):*
<details><summary><i>Previously, elkmaster wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry for being late with this comment, but one thing that I was hoping to accomplish with these updates was to use the [design tokens](https://github.com/cockroachdb/ui/tree/master/packages/design-tokens) in the UI repo as a dependency for this update. As I was reviewing this I realized that those colors are out of date from an update that was made to the Figma mock last week. So I am not requesting you make this change at the moment, but something to be aware of. I would like to see us reduce the duplication between `admin-ui-components` and `ui` as much as we can going forward.

In the meantime, I will see about getting the UI tokens updated.

---


<!-- Sent from Reviewable.io -->

2020-12-02 09:03 UTC, koorosh approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/44)* status: all files reviewed, 1 unresolved discussion (waiting on @elkmaster)



<!-- Sent from Reviewable.io -->

2020-12-11 09:39 UTC, merged